import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";
import Nav from "@/components/shared/Nav/Nav";
// import { auth } from "../../auth";
// import { SessionProvider } from "next-auth/react";
// import Footer from "@/components/shared/Footer/Footer";
// import FinalCTA from "@/components/shared/FinalCTA/FinalCTA";
// import { Toaster } from "react-hot-toast";

const DMSans = localFont({
  src: "../../public/fonts/DMSans.woff2",
  variable: "--DMSans",
  display: "swap",
});

const mulish = Mulish({
  variable: "--mulish",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const session = await auth();

  return (
    // <SessionProvider session={session}>
    <html lang='en'>
      <body className={`${DMSans.variable} ${mulish.variable}`}>
        {/* <Toaster
            position='top-right'
            toastOptions={{
              className: "toastFont",
            }}
          /> */}
        <Nav />
        {children}
        {/* <FinalCTA /> */}
        {/* <Footer /> */}
      </body>
    </html>
    // </SessionProvider>
  );
}
